### PR TITLE
set up Travis CI?

### PR DESCRIPTION
**Pull request by tkelman**
Brilliant that this builds. Any interest in setting up Travis CI? It's a free service you can turn on at www.travis-ci.org. See https://api.travis-ci.org/jobs/56062942/log.txt?deansi=true for what the output looks like.

### CODE REVIEW

**Comment by Shizmob** [comment]
Hi!

I wouldn't be opposed to using Travis, but the issue is that most actual useful code is not within this repository, and the only commits here would be either the addition of new targets or small version bumps. Ideally if we were to use a CI service, it would run on the repositories with the actual useful code and be triggered on every commit there, instead of occasionally being ran here when we bump a version or make small fixes for the build script.

Of course, this is all fully up to @midipix to decide, these are just my two cents.

**Comment by tkelman** [comment]
Yeah, that had occurred to me. The master build script is here but the useful code is in the other repos. With appropriate webhook plumbing, things could maybe be set up to trigger a new build here on every commit to one of the other repos? That wouldn't help too much with branches or PR's for the other repos, but it could at least be a start...

**Comment by Shizmob** [comment]
I think maybe a better approach to this, if we were to use Travis, would be to hook it up to the main GCC patches repo and then just clone the build script from this repo as part of the build preparation steps. Maybe some webhooks could then indeed be used to trigger a build from the other, smaller, repos (mmglue, psxstub/psxscl and portage) - with GitHub's API, doing something on a new PR should not be a problem either.

I'm not sure if Travis offers an API to manually invoke a build however, it is something that would need looking into.

**Comment by tkelman** [comment]
Perhaps a different yml file for each repo that just clones every other piece except itself. Little messier but maybe more straightforward than webhooks. I could give that a shot, but will wait for an overall opinion on whether there's a desire to use Travis first.

**Comment by midipix** [comment]
I am not overly familiar with Travis and might be missing something trivial, but here is my question: for all I can tell from 'sudo' and 'libgmp-dev' (as opposed to ssh@localhost and libgmp-devel, for instance), the .yml file is both distro- and package-manager-specific, which makes me think that it might be more appropriate for distro maintainers, rather than the basic cbb-gcc repo. One objective of cbb-gcc is to allow building from source in a way that is both distro- and os-agnostic -- granted, of course, that the os and shell environments are suitable for building gcc to begin with. Any thoughts?

**Comment by tkelman** [comment]
Yes, this yml file is distro-specific. Travis CI is a hosted continuous integration service. On every pull request and push, this yml file defines the steps that get run on an Ubuntu VM. That checks that things keep working, as a sanity check against your local tests (or in case you forget to test some change).

**Comment by midipix** [comment]
Thanks. I will be creating soon a repo for useful contributions, samples, templates, etc., with a folder for build-related add-ons, which I think would be the best place for .yml and similar files. Does that work?

**Comment by tkelman** [comment]
It does no good as a template, it's only useful if you want to use and enable the service.

**Comment by midipix** [comment]
Apparently I did miss something trivial:-)  If all that using the service takes is a simple .yml file then I am not too opposed to that. The real question is what needs to be done otherwise for that to work. As Shiz mentioned, cbb-gcc only contains the build scripts, whereas the code that gets built consists in several other repositories (cbb-gcc-$ver, musl, portage, mmglue, etc.)  Will using Travis require setting webhooks and additional .yml files for all of the sub-components?  As I should probably mention, I now perform a build of the entire toolchain on two to three different machines (ubuntu, centos, opensuse) prior to pushing any of the commits to cbb-gcc-$ver to the public repository.

**Comment by tkelman** [comment]
If that's the case, then you have things covered and maybe don't need Travis. It is a nice way to have the build logs be publicly visible. I was pleasantly surprised when `x86_64-nt64-midipix-gcc` only took 10 minutes to build for example.

I think it would either be webhooks for all but one repo, or slightly different yml files in each repo. In the separate yml files I would clone the master build script, make a symlink from what travis checks out (either the push or the PR) to the expected default location for that component, then I think things might work fine?

**Comment by Shizmob** [comment]
I think an independent third-party verification can never hurt. Slightly differring .yml files for every repo that just clone this script and run it would work fine, yes.

**Comment by midipix** [comment]
Third-party verification would be an excellent addition to the project, and I'd be happy to set up the necessary git hooks for automatic commit notifications. The other thing that comes to mind is to publish logs of my own builds as an extra reference.

**Comment by tkelman** [comment]
Great, then do you want to enable this repository at travis-ci.org? Note that some mitigation of the log length is necessary since Travis fails a build if the log gets over 4 MB in size. The `-s` flag seems to be good enough for the time being, other suggestions welcome.

There is also some configuration that can be modified to make the builds run on a Docker-container worker (starts up faster), but that would have to wait for them to add libmpc-dev to an apt whitelist. I filed a request for that.

**Comment by midipix** [comment]
Since this seems to be unintrusive as far as the public repository goes then certainly, let's set this up.  For the '-s' flag, let's have an additional shell variable passed to make, and have the .yml file set that variable upon calling ./cbb-midipix.sh.  This will provide Travis with a report short enough to handle while leaving the default build process unaffected. If you wouldn't mind joining #midipix, then I'd suggest going through the rest of the technical details there.

**Comment by tkelman** [comment]
How about appending to `MAKEFLAGS` instead of overwriting it?

**Pull request closed without merging**
